"""Fix Contact model nullable fields

Revision ID: bf0f65987044
Revises: 
Create Date: 2025-06-23 15:01:19.300144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0f65987044'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('street_and_nr',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('street_and_nr',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
