"""Changed Column names

Revision ID: ed38532f62d1
Revises: 0e05fe8aa995
Create Date: 2025-08-04 20:58:29.777290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed38532f62d1'
down_revision = '0e05fe8aa995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_block_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_block_list_user_id'))

    op.drop_table('token_block_list')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contact_place', sa.String(length=200), nullable=True))
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_column('last_contact_place')
        batch_op.drop_column('last_contact_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_contact_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('last_contact_place', sa.VARCHAR(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('contact_place')
        batch_op.drop_column('contact_date')

    op.create_table('token_block_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('revoked_at', sa.DATETIME(), nullable=True),
    sa.Column('expires', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('token_block_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_block_list_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
